kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: k8s-storage-policy
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "k8s-storage-policy"
  #  diskformat: thin
  #  datastore: vsanDatastore
