apiVersion: v1
kind: Pod
metadata:
    name: thinclaimpod
spec:
    containers:
    - name: test-container
      image: "wcp-docker-ci.artifactory.eng.vmware.com/vmware/photon:1.0"
      command: ["/bin/sh", "-c", "echo 'hello' > /mnt/volume1/index.html  && chmod o+rX /mnt /mnt/volume1/index.html && while true ; do sleep 2 ; done"]
      volumeMounts:
      - name: test-volume
        mountPath: /mnt/volume1
    restartPolicy: Never
    volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: mysql-pvc-claim
